# Generated by Django 6.0.6 on 2026-06-10 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_terapi', models.CharField(choices=[('terapi_wicara', 'Terapi Wicara'), ('terapi_okupasi', 'Terapi Okupasi'), ('terapi_fisik', 'Terapi Fisik'), ('terapi_perilaku', 'Terapi Perilaku'), ('terapi_sensori', 'Terapi Integrasi Sensori'), ('konsultasi', 'Konsultasi')], max_length=100, verbose_name='Jenis Terapi')),
                ('deskripsi_terapi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Terapi')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('frekuensi', models.CharField(help_text='Contoh: 2x seminggu', max_length=50, verbose_name='Frekuensi')),
                ('durasi_per_sesi', models.IntegerField(default=60, help_text='Durasi setiap sesi dalam menit', verbose_name='Durasi per Sesi (menit)')),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('berjalan', 'Berjalan'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='terjadwal', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terapi', to='assessments.assessmentmedis', verbose_name='Assessment Terkait')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapi', to='patients.pasien', verbose_name='Pasien')),
                ('terapis', models.ForeignKey(limit_choices_to={'role': 'terapis'}, on_delete=django.db.models.deletion.PROTECT, related_name='terapi_ditangani', to='users.user', verbose_name='Terapis')),
            ],
            options={
                'verbose_name': 'Terapi',
                'verbose_name_plural': 'Terapi',
                'db_table': 'terapi',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringTerapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_sesi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Sesi')),
                ('durasi_aktual', models.IntegerField(blank=True, help_text='Durasi aktual sesi dalam menit', null=True, verbose_name='Durasi Aktual (menit)')),
                ('kehadiran', models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin')], default='hadir', max_length=20, verbose_name='Kehadiran')),
                ('kondisi_pasien', models.TextField(verbose_name='Kondisi Pasien')),
                ('catatan_perkembangan', models.TextField(verbose_name='Catatan Perkembangan')),
                ('pencapaian_target', models.TextField(blank=True, null=True, verbose_name='Pencapaian Target')),
                ('rekomendasi_sesi_berikutnya', models.TextField(blank=True, null=True, verbose_name='Rekomendasi Sesi Berikutnya')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_terapi', to='patients.pasien', verbose_name='Pasien')),
                ('terapis', models.ForeignKey(limit_choices_to={'role': 'terapis'}, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_dicatat', to='users.user', verbose_name='Terapis')),
                ('terapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='therapies.terapi', verbose_name='Terapi')),
            ],
            options={
                'verbose_name': 'Monitoring Terapi',
                'verbose_name_plural': 'Monitoring Terapi',
                'db_table': 'monitoring_terapi',
                'ordering': ['-tanggal_sesi'],
            },
        ),
        migrations.AddIndex(
            model_name='terapi',
            index=models.Index(fields=['pasien', 'status'], name='terapi_pasien__39344a_idx'),
        ),
        migrations.AddIndex(
            model_name='terapi',
            index=models.Index(fields=['terapis'], name='terapi_terapis_5a1d57_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringterapi',
            index=models.Index(fields=['pasien', 'tanggal_sesi'], name='monitoring__pasien__ca5055_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringterapi',
            index=models.Index(fields=['terapi'], name='monitoring__terapi__4421ad_idx'),
        ),
    ]
