# Generated by Django 6.0.6 on 2026-06-10 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('queues', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_assessment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Assessment')),
                ('keluhan_utama', models.TextField(verbose_name='Keluhan Utama')),
                ('riwayat_penyakit', models.TextField(blank=True, null=True, verbose_name='Riwayat Penyakit')),
                ('hasil_pemeriksaan', models.TextField(verbose_name='Hasil Pemeriksaan Fisik')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('catatan_medis', models.TextField(blank=True, null=True, verbose_name='Catatan Medis Tambahan')),
                ('rencana_terapi', models.TextField(verbose_name='Rencana Terapi')),
                ('frekuensi_terapi', models.CharField(blank=True, help_text='Contoh: 2x seminggu, 3x sebulan', max_length=50, null=True, verbose_name='Frekuensi Terapi')),
                ('durasi_terapi', models.IntegerField(blank=True, help_text='Durasi terapi dalam minggu/bulan', null=True, verbose_name='Durasi Terapi (minggu)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('dirujuk', 'Dirujuk')], default='draft', max_length=20, verbose_name='Status')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
                ('antrian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='queues.antrian', verbose_name='Antrian Terkait')),
                ('dokter', models.ForeignKey(limit_choices_to={'role': 'dokter'}, on_delete=django.db.models.deletion.PROTECT, related_name='assessments_dilakukan', to='users.user', verbose_name='Dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.pasien', verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Assessment Medis',
                'verbose_name_plural': 'Assessment Medis',
                'db_table': 'assessment_medis',
                'ordering': ['-tanggal_assessment'],
                'indexes': [models.Index(fields=['pasien', 'tanggal_assessment'], name='assessment__pasien__471d1d_idx'), models.Index(fields=['dokter'], name='assessment__dokter__671d65_idx')],
            },
        ),
    ]
