# Generated by Django 6.0.6 on 2026-06-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_antrian', models.CharField(editable=False, help_text='Nomor antrian unik per hari', max_length=20, unique=True, verbose_name='Nomor Antrian')),
                ('jenis_layanan', models.CharField(choices=[('assessment', 'Assessment Medis'), ('terapi_wicara', 'Terapi Wicara'), ('terapi_okupasi', 'Terapi Okupasi'), ('terapi_fisik', 'Terapi Fisik'), ('terapi_perilaku', 'Terapi Perilaku'), ('konsultasi', 'Konsultasi')], max_length=30, verbose_name='Jenis Layanan')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('dalam_proses', 'Dalam Proses'), ('selesai', 'Selesai'), ('tidak_hadir', 'Tidak Hadir'), ('batal', 'Dibatalkan')], default='menunggu', max_length=20, verbose_name='Status')),
                ('prioritas', models.CharField(choices=[('normal', 'Normal'), ('prioritas', 'Prioritas')], default='normal', max_length=10, verbose_name='Prioritas')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pendaftaran')),
                ('tanggal_panggil', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Dipanggil')),
                ('tanggal_mulai', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Mulai Layanan')),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai Layanan')),
                ('estimasi_waktu_tunggu', models.IntegerField(default=0, help_text='Estimasi waktu tunggu dalam menit', verbose_name='Estimasi Waktu Tunggu (menit)')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dikelola_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antrian_dikelola', to='users.user', verbose_name='Dikelola Oleh')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antrian', to='patients.pasien', verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Antrian',
                'verbose_name_plural': 'Antrian',
                'db_table': 'antrian',
                'ordering': ['-tanggal_daftar'],
            },
        ),
        migrations.CreateModel(
            name='LogNotifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=20, verbose_name='Metode Notifikasi')),
                ('tujuan', models.CharField(max_length=100, verbose_name='Tujuan (Nomor HP/Email)')),
                ('pesan', models.TextField(verbose_name='Isi Pesan')),
                ('status', models.CharField(choices=[('terkirim', 'Terkirim'), ('gagal', 'Gagal'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Status Pengiriman')),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Kirim')),
                ('tanggal_dibaca', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Dibaca')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Pesan Error (jika gagal)')),
                ('antrian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_notifikasi', to='queues.antrian', verbose_name='Antrian')),
            ],
            options={
                'verbose_name': 'Log Notifikasi',
                'verbose_name_plural': 'Log Notifikasi',
                'db_table': 'log_notifikasi',
                'ordering': ['-tanggal_kirim'],
            },
        ),
        migrations.AddIndex(
            model_name='antrian',
            index=models.Index(fields=['status'], name='antrian_status_6fe896_idx'),
        ),
        migrations.AddIndex(
            model_name='antrian',
            index=models.Index(fields=['tanggal_daftar'], name='antrian_tanggal_7093c7_idx'),
        ),
        migrations.AddIndex(
            model_name='antrian',
            index=models.Index(fields=['pasien', 'status'], name='antrian_pasien__1a20c6_idx'),
        ),
    ]
