# Generated by Django 6.0.6 on 2026-06-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrm', models.CharField(editable=False, help_text='Nomor Rekam Medis unik pasien', max_length=20, unique=True, verbose_name='Nomor Rekam Medis')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap Anak')),
                ('nik', models.CharField(help_text='Nomor Induk Kependudukan 16 digit', max_length=16, unique=True, verbose_name='NIK Anak')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('nama_wali', models.CharField(max_length=200, verbose_name='Nama Orang Tua/Wali')),
                ('nik_wali', models.CharField(max_length=16, verbose_name='NIK Orang Tua/Wali')),
                ('hubungan', models.CharField(choices=[('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Wali', 'Wali Lainnya')], max_length=20, verbose_name='Hubungan dengan Anak')),
                ('nomor_telepon_wali', models.CharField(max_length=15, verbose_name='Nomor Telepon/WhatsApp Wali')),
                ('email_wali', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Wali')),
                ('alamat_lengkap', models.TextField(verbose_name='Alamat Lengkap')),
                ('rt_rw', models.CharField(blank=True, max_length=20, verbose_name='RT/RW')),
                ('kelurahan', models.CharField(blank=True, max_length=100, verbose_name='Kelurahan')),
                ('kecamatan', models.CharField(blank=True, max_length=100, verbose_name='Kecamatan')),
                ('kota', models.CharField(default='Yogyakarta', max_length=100, verbose_name='Kota/Kabupaten')),
                ('provinsi', models.CharField(default='DI Yogyakarta', max_length=100, verbose_name='Provinsi')),
                ('golongan_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True, verbose_name='Golongan Darah')),
                ('alergi', models.TextField(blank=True, help_text='Riwayat alergi (jika ada)', null=True)),
                ('status_aktif', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('tanggal_registrasi', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Registrasi')),
                ('tanggal_update_terakhir', models.DateTimeField(auto_now=True, verbose_name='Tanggal Update Terakhir')),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien',
                'db_table': 'pasien',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatKunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Kunjungan')),
                ('tujuan_kunjungan', models.CharField(max_length=200, verbose_name='Tujuan Kunjungan')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kunjungan', to='patients.pasien', verbose_name='Pasien')),
            ],
            options={
                'verbose_name': 'Riwayat Kunjungan',
                'verbose_name_plural': 'Riwayat Kunjungan',
                'db_table': 'riwayat_kunjungan',
                'ordering': ['-tanggal_kunjungan'],
            },
        ),
    ]
