# Generated by Django 6.0.6 on 2026-06-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_laporan', models.CharField(choices=[('harian', 'Laporan Harian'), ('mingguan', 'Laporan Mingguan'), ('bulanan', 'Laporan Bulanan'), ('evaluasi_pasien', 'Evaluasi Perkembangan Pasien'), ('statistik', 'Laporan Statistik')], max_length=30, verbose_name='Tipe Laporan')),
                ('judul_laporan', models.CharField(max_length=200, verbose_name='Judul Laporan')),
                ('periode_mulai', models.DateField(verbose_name='Periode Mulai')),
                ('periode_selesai', models.DateField(verbose_name='Periode Selesai')),
                ('ringkasan_isi', models.TextField(verbose_name='Ringkasan Isi Laporan')),
                ('data_lengkap', models.JSONField(blank=True, help_text='Data lengkap laporan dalam format JSON', null=True, verbose_name='Data Lengkap')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='laporan/pdf/', verbose_name='File PDF')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai'), ('terkirim', 'Terkirim')], default='draft', max_length=20, verbose_name='Status')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
                ('tanggal_dikirim', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Dikirim')),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_dibuat', to='users.user', verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'db_table': 'laporan',
                'ordering': ['-tanggal_dibuat'],
                'indexes': [models.Index(fields=['tipe_laporan', 'tanggal_dibuat'], name='laporan_tipe_la_48a8c5_idx'), models.Index(fields=['dibuat_oleh'], name='laporan_dibuat__921ddd_idx')],
            },
        ),
    ]
